### ISSUE TITLE
The Heatmap shows the wrong day

### ISSUE THREAD

**Issue by wismie** [Quorafind/Obsidian-Memos#77] opened 2022-01-23 12:40 UTC
When I enter a memo, let's say today (jan 23), the memo shows that is has been created on the 22nd. I do not know if it is due to the fact that I am in the CET+1 timezone?

![image](https://user-images.githubusercontent.com/32569374/150678735-b0b87153-af51-44c8-914e-4fea4514bbca.png)

**Comment by Quorafind** [comment] 2022-01-23 12:43
It is werid, I need to ask someone to see if he has the same issue

**Comment by wismie** [comment] 2022-01-23 12:50
BTW this happens to all items. I installed the plugin yesterday and did enter some test memos, they are all marked as being created on Friday

![image](https://user-images.githubusercontent.com/32569374/150679189-b2d7e555-a976-4f51-afad-22a03e73efe2.png)

**Comment by Quorafind** [comment] 2022-01-23 12:56
Fixed in next version

**Comment by wismie** [comment] 2022-01-23 13:25
Thanks!

**Comment by BricoleurSoul** [comment] 2022-01-25 20:16
NOT fixed in 1.7.9

**Comment by Quorafind** [comment] 2022-01-25 23:31
Need more effort to do it. Should be 1.8.0

**Comment by Quorafind** [comment] 2022-01-26 06:04
@wismie @BricoleurSoul Could you try 1.7.10 to see if this issue remains?

**Comment by BricoleurSoul** [comment] 2022-01-26 07:23
> @wismie @BricoleurSoul Could you try 1.7.10 to see if this issue remains?

Wonderful - it works as intended, Thanks for the quick update.

**Comment by Quorafind** [comment] 2022-01-26 07:25
Thanks for quick reply.

**Closed by Quorafind** 2022-01-26 07:25 UTC
